# coding: utf-8

"""
    Kagi API

    The Kagi API provides programmatic access to data that powers our search results & more.  Get started on the [API Dashboard](https://kagi.com/api) to set up billing, manage API keys, and more. ### Official Client Libraries We offer the following libraries you can use to interact with the Kagi API. These are generated from an OpenAPI spec. If you have a language you would like to use and it's not in the list, send us a message and we will add it to the list if it is supported. Or you can use the [spec](https://kagi.redocly.app/_spec/openapi.yaml?download) to build your own custom library. - [Golang](https://github.com/kagisearch/kagi-openapi-golang) - [Python](https://github.com/kagisearch/kagi-openapi-python) - [TypeScript](https://github.com/kagisearch/kagi-openapi-typescript) - [Rust](https://github.com/kagisearch/kagi-openapi-rust) ### API Status Our existing API, the \"v0\" beta API, is being replaced with a new version that will be available publicly soon. As changes are made, we will be updating the documentation below when the new features become available. See the [Support and Community](https://help.kagi.com/kagi/support-and-community/) section for details. ### Pricing See our [API Pricing](https://kagi.com/api/pricing) page for standard rates. ### GitHub Discussions This is the preferred venue for bug reports and feature requests. - [Bug Reports](https://github.com/kagisearch/kagi-docs/issues/new/choose) - [Q&A Forum](https://github.com/kagisearch/kagi-docs/discussions/categories/q-a?discussions_q=category%3AQ%26A+label%3Aproduct%3Akagi_search_api) - [API Feature Requests](https://github.com/kagisearch/kagi-docs/discussions/categories/kagi-search-api-feature-requests-ideas) ### Discord Join our [Discord](https://kagi.com/discord)! Good for quick questions or chatting about things you've made with our APIs!

    The version of the OpenAPI document: v1
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_request import SearchRequest

class TestSearchRequest(unittest.TestCase):
    """SearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchRequest:
        """Test SearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchRequest`
        """
        model = SearchRequest()
        if include_optional:
            return SearchRequest(
                query = '',
                workflow = 'search',
                format = 'json',
                lens_id = '',
                lens = openapi_client.models.search_request_lens.search_request_lens(
                    sites_included = [
                        ''
                        ], 
                    sites_excluded = [
                        ''
                        ], 
                    keywords_included = [
                        ''
                        ], 
                    keywords_excluded = [
                        ''
                        ], 
                    file_type = '', 
                    time_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    time_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    time_relative = 'day', 
                    search_region = '', ),
                timeout = 0.5,
                page = 1,
                limit = 1,
                filters = openapi_client.models.search_request_filters.search_request_filters(
                    region = '', 
                    after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                extract = openapi_client.models.search_request_extract.search_request_extract(
                    count = 1, 
                    timeout = 0.5, ),
                personalizations = openapi_client.models.search_request_personalizations.search_request_personalizations(
                    domains = [
                        openapi_client.models.search_request_personalizations_domains_inner.search_request_personalizations_domains_inner(
                            domain = '', 
                            bias = 1.337, )
                        ], 
                    regexes = [
                        openapi_client.models.search_request_personalizations_regexes_inner.search_request_personalizations_regexes_inner(
                            regex = '', 
                            replacement = '', )
                        ], )
            )
        else:
            return SearchRequest(
                query = '',
        )
        """

    def testSearchRequest(self):
        """Test SearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
